apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-admin
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-admin
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-admin
    spec:
      containers:
        - name: admin
          image: {{ .Values.admin.image }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
spec:
  selector:
    app: {{ .Release.Name }}-admin
  ports:
    - port: 80
      targetPort: 80

